test:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  tty: true
  volumes_from: 
    - cache 
  links:
    - db
  environment:
    TLR_TEST1: testvalue1

builder:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes_from:
    - cache
  entrypoint: "entrypoint.sh"
  command: ["pip", "wheel", "--no-index", "-f /build", "."] 

agent: 
  image: akr19/ansible
  links: 
    - db
  environment: 
    PROBE_HOST: "db"
    PROBE_PORT: "3306"
  command: ["probe.yml"]

db:
  image: akr19/calcbackend-db:latest 
  hostname: db
  command: --default-authentication-plugin=mysql_native_password
  expose: 
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: password1
  volumes:
    - ../../dbschema:/docker-entrypoint-initdb.d

cache:
  build: ../../
  dockerfile: docker/dev/Dockerfile
  volumes: 
    - /tmp/cache:/cache
  entrypoint: "true"


