app: 
  build: ../../
  dockerfile: docker/release/Dockerfile
  links:
    - db
  volumes_from:
    - webroot
  ports:
    - "1234:1234"
  command:
    - uwsgi
    - "--socket /var/www/calcbackend/calcbackend.sock"  
      #- "--http-socket 0.0.0.0:1234"
    - "--module mywsgi"
    - "--chdir /appenv/bin"
    - "--chmod-socket=666"
      #- "--module calcbackend.wsgi"
    - "--master"
    - "--die-on-term"

test: 
  image: akr19/calcbackend-specs
  links: 
    - nginx
  environment: 
    URL: http://nginx:8000

nginx:
  build: .
  dockerfile: Dockerfile.nginx
  links:
    - app
  ports:
    - "8000:8000"
  volumes_from:
    - webroot

webroot:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes:
    - /var/www/calcbackend
  entrypoint: "true"

db:
  image: mysql:8.0.13
  command: --default-authentication-plugin=mysql_native_password
  expose: 
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: password1
  volumes:
    - ../../dbschema:/docker-entrypoint-initdb.d

agent:
  image: jmenga/ansible
  links:
    - db
  environment:
    PROBE_HOST: "db"
    PROBE_PORT: "3306"
  command: ["probe.yml"]

